### ISSUE TITLE
Cannot install from zip file

### ISSUE THREAD

**Issue by Tanja-108** [themesalmond/moodle-local_almondbpage#2]
Hi, 

I do have a problem when trying to instal the plugin as a zip-file from the moodle admin panel plugins tab.

It is unable to detect the plugin type first. When I am choosing "local plugin" and try to install then - nothing happens and the selected zip-file disappears. 

You can find a screencast attached. 

I cannot reach out to the server by myself. 

I have admin rights to install plugins from the plugins tab only. 

It is the first time I face such a problem. Do you have an idea, what to do? 

Thank you, 

Tanja

https://user-images.githubusercontent.com/82780912/209480972-89f331d4-d684-4772-b974-21603633c84f.mov

**Comment by themesalmond** [comment]
Hello,
Please read the readme file inside the file. 
Or browse here :
https://github.com/themesalmond/moodle-local_almondbpage/blob/main/README.md

**Comment by Tanja-108** [comment]
Thank you. 

I somehow have overseen this
