### ISSUE TITLE
edit section in Moodle course

### ISSUE THREAD

**Issue by aymannoor82** [themesalmond/moodle-local_almondbpage#3]
Hi,

After upgrade to Moodle 4.4.1 and using Almond theme, we can't edit the section inside the course, when we press on edit 3 dots for the section the small screen shown below the activities and we couldn't press on all the buttons as the attached image.

![Moodle-Almond-Capture](https://github.com/user-attachments/assets/d35fce76-003c-421c-a38c-a006c1ea9e12)

Thanks

**Comment by themesalmond** [comment]
Hello,
We updated the theme.
You can download and use the updated version.
Best Regards
Almond Themes
